CREATE SCHEMA sport;

USE sport;

CREATE TABLE ADDRESS
(
    ADDRESS_ID CHAR(5) NOT NULL,
    ADDRESS_NAME VARCHAR(45) NOT NULL,
    ZIP_CODE INTEGER NOT NULL ,
    CONSTRAINT PK_ADDRESS PRIMARY KEY(ADDRESS_ID),
    CONSTRAINT UQ_ZIP_CODE UNIQUE (ZIP_CODE)
);

CREATE TABLE TEAM
(
    TEAM_ID CHAR(5) NOT NULL,
    TEAM_NAME VARCHAR(45) NOT NULL,
    PHONE VARCHAR(45),
    ADDRESS_ID CHAR(5) NOT NULL,
    CONSTRAINT PK_TEAM PRIMARY KEY(TEAM_ID),
    CONSTRAINT FK_TEAM_ADDRESS FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE TABLE PLAYER
(
    PLAYER_ID CHAR(5) NOT NULL,
    PLAYER_NAME VARCHAR(45)	NOT NULL,
    PLAYER_NO INTEGER,
    TEAM_ID CHAR(5)	NOT NULL,
    CONSTRAINT PK_PLAYER PRIMARY KEY(PLAYER_ID),
    CONSTRAINT FK_Player_Team FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID)
);